name: build a Nodejs App and push to Docker hub

on:
  push:
    branches: 
        - main
  workflow_dispatch:
jobs:
   build-and-push:
       name: whatever
       runs-on: ubuntu-latest
       strategy:
          matrix:
             node_version: ['18.x', '20.x','22.x']
       steps:
         - name: checkout the repository
           uses: actions/checkout@v4 
         - name: set up nodejs
           uses: actions/setup-node@v4
           with:
             node-version: ${{ matrix.node_version }}
         - name: install dependencies
           run: |
             cd dive-react-app
             npm install 
             npm run lint
             npm run build
  
